let Animals: [String:[String]] = [
    "mouse": ["мышь"],
    "cat": ["кот", "кошка"],
    "deer": ["олень"],
    "lion": ["лев"],
    "bear": ["медведь"],
    "wolf": ["волк"],
    "elephant": ["слон"],
    "rabbit": ["кролик"],
    "donkey": ["осел"],
    "leopard": ["леопард"],
    "tiger": ["тигр"],
    "monkey": ["обезьяна"],
    "fox": ["лиса"],
    "llama": ["лама"],
    "squirrel": ["белка"],
    "kangaroo": ["кенгуру"],
    "giraffe": ["жираф"],
    "hippopotamus": ["бегемот"],
    "rhinoceros": ["носорог"],
    "dog": ["собака"],
    "rat": ["крыса"],
    "koala": ["коала"],
    "panda": ["панда"],
    "chipmunk": ["бурундук"],
    "hamster": ["хомяк"],
    "beaver": ["бобр"],
    "guinea pig": ["морская свинка"],
    "armadillo": ["броненосец"],
    "bat": ["летучая мышь"],
    "gopher": ["суслик"],
    "porcupine": ["дикобраз"],
    "horse": ["лошадь"],
    "camel": ["верблюд"],
    "moose": ["американский лось"],
    "raccoon": ["енот"],
    "skunk": ["скунс"],
    "seal": ["тюлень"],
    "hyena": ["гиена"],
    "possum": ["опоссум"],
    "buffalo": ["буйвол"],
    "bison": ["бизон"],
    "grizzly": ["гризли"],
    "hedgehog": ["еж"]
]
