import Foundation

let BodyParts: [String:[String]] = [
    "eyes": ["глаза"],
    "eyebrows" : ["брови"],
    "hair": ["волосы"],
    "hand": ["рука"],
    "neck": ["шея"],
    "cheeck": ["щека"],
    "chin": ["подбородок"],
    "lips": ["губы"],
    "mouth": ["рот"],
    "ears": ["уши"],
    "fingers": ["пальцы"],
    "stomach": ["живот"],
    "spine": ["позвоночник"],
    "muscles": ["мышцы"],
    "smooth muscle": ["гладкая мышечная ткань"],
    "small intestine": ["тонкий кишечник"],
    "skeletal muscles" : ["мышцы скелета"],
    "nerves": ["нервы"],
    "liver": ["печень"],
    "lungs": ["легкие"],
    "kidneys": ["почки"],
    "heart": ["сердце"],
    "brain": ["мозг"],
    "arteries": ["артерии"],
    "blood": ["кровь"],
    "DNA": ["ДНК"],
    "ankle": ["щиколотка"],
    "armpit": ["подмышка"],
    "leg": ["нога"],
    "feet": ["стопы"],
    "back": ["спина"],
    "knee": ["колено"],
    "toes": ["носки"],
    "bust": ["бюст, женская грудь"],
    "buttock": ["ягодица"],
    "chest": ["грудная клетка"],
    "elbow": ["локоть"],
    "freckles": ["веснушки"],
    "limbs": ["конечности"],
    "shoulder": ["плечо"],
    "nipple": ["сосок"],
    "skin": ["кожа"],
    "wrinkles": ["морщины"],
    "fingerprints": ["узоры на пальцах", "отпечатки пальцев"],
    "heel": ["пятка"],
    "wrist": ["запястье"],
    "tears": ["слёзы"],
    "sweat": ["пот"],
    "nose": ["нос"],
    "calvity": ["лысина"],
    "beard": ["борода"],
    "tooth": ["зуб"],
    "corner of the mouths": ["уголок рта"],
    "ear drum": ["барабанная перепонка"],
    "earlobe": ["мочка уха"],
    "eyelashes": ["ресницы"],
    "forehead": ["лоб"],
    "face": ["лицо"],
    "tongue": ["язык"],
    "head": ["голова"],
    "molar": ["коренной зуб"],
    "scalp": ["кожа головы"],
    "taste buds": ["вкусовые рецепторы"],
    "tonsil": ["миндалина"],
    "biceps": ["бицепс"],
    "calf": ["икроножная мышцы"],
    "quadriceps": ["квадрицепс"],
    "trapezius muscle": ["трапециевидная мышца"],
    "abdominal cavity": ["брюшная полость"],
    "aorta": ["аорта"],
    "appendix": ["аппендикс"],
    "bronchi": ["бронхи"],
    "cerebellum": ["мозжечок"],
    "larynx": ["гортань"],
    "pharynx": ["глотка"],
    "hypophysis": ["гипофиз"],
    "spleen": ["селезёнка"],
    "throat": ["горло"],
    "viscera": ["внутренности"],
    "alveolar bone": ["Альвеолярная кость"],
    "hips": ["бедро"],
    "thigh": ["бедро"],
    "nails": ["ногти"],
    "waist": ["талия"],
    "forearm": ["предплечье"],
    "instep": ["предплюсна"],
    "toenail": ["ноготь на ноге"],
    "mole": ["родинка"],
    "moustache": ["усы"],
    "knuckle": ["костяшки пальцев"],
    "eyelid": ["веко"],
    "index finger": ["указательный палец"],
    "middle finger": ["средний палец"],
    "ring finger": ["безымянный палец"],
    "little finger": ["мизинец"],
    "palm": ["ладонь"],
    "trachea": ["трахея"],
    "gallbladder": ["желчный пузырь"],
    "urinary bladder": ["мочевой пузырь"],
    "canine": ["почки"],
    "hard palate": ["твёрдое нёбо"],
    "soft palate": ["мягкое нёбо"],
    "uvula": ["нёбный язычок"],
    "gums": ["десны"],
    "incisor": ["резец"],
    "triceps": ["трицепс"],
    "serratus": ["зубчатая мышца"],
    "septum": ["перегородка между ноздрями"],
    "nostrils": ["ноздри"],
    "root": ["корень зуба"],
    "stomachache": ["боль в животе"],
    "premolar": ["малый кроёной зуб"],
    "nasal sinus": ["носовые пазухи"],
    "iris": ["радужка"],
    "external corner of the eye": ["внешний угол глаза"],
    "dimple of chin": ["ямочка на подбородке"],
    "earwax": ["ушная сера"],
    "cornea": ["роговица"],
    "dandruff": ["перхоть"],
    "crystalline": ["хрусталик"],
    "crown of the tooth": ["коронка зуба"],
    "cyst": ["киста"],
    "bile": ["желчь"],
    "thumb": ["большой палец"],
    "plantar arch": ["подошвенная дуга"],
    "corpus": ["туловище"],
    "trunk": ["туловище"],
    "navel": ["пупок"],
    "belly button": ["пупок"],
    "lumbar region": ["поясничный отдел"],
    "groin": ["пах"],
    "kneecap": ["коленная чашечка"],
    "brain steam": ["мозговой ствол"],
    "cerebrum": ["головной мозг"],
    "spinal cord": ["спинной мозг"],
    "optical lobe": ["затылочная доля"],
    "frontal lobe": ["лобная доля"],
    "joint": ["сустав"],
    "hormones": ["гормоны"],
    "pancreas": ["поджелудочная железа"],
    "vein": ["вена, жила"],
    "digestive system": ["пищеварительная система"],
    "lymphatic system": ["лимфатическая система", "имунная система"],
    "pigmentation": ["пигментация"],
    "skull": ["череп"],
    "skeleton": ["скелет"]
]
