let Clothes: [String:[String]] = [
    "suit": ["костюм"],
    "jacket": ["куртка"],
    "scarf": ["шарф"],
    "tie": ["галстук"],
    "blouse": ["блузка"],
    "shirt": ["рубашка"],
    "nightdress": ["ночная рубашка"],
    "swimsuit": ["купальник"],
    "cardigan": ["кардиган"],
    "jeans": ["джинсы"],
    "raincoat": ["плащ"],
    "shorts": ["шорты"],
    "sweater": ["свитер"],
    "t-shirt": ["Футболка"],
    "vest": ["жилет"],
    "waistcoat": ["жилет"],
    "socks": ["носки"],
    "stockings": ["чулки"],
    "tights": ["колготки"],
    "gloves": ["перчатка"],
    "pyjamas": ["пижама"],
    "sunglasses": ["темные очки"],
    "underpants": ["кальсоны трусы"],
    "briefs": ["трусы"],
    "skirt": ["юбка"],
    "trousers": ["брюки"],
    "uniform": ["форменная одежда"],
    "necklace": ["ожерелье"],
    "belt": ["ремень пояс"],
    "glasses": ["очки"],
    "jumper": ["джемпер"],
    "ring": ["кольцо"],
    "earrings": ["серьги"],
    "beads": ["бусы", "бисер"],
    "watch": ["часы"],
    "boots": ["ботинки"],
    "pants": ["брюки"],
    "shoes": ["туфли"],
    "sandals": ["сандалии"],
    "pullover": ["пуловер"],
    "trainers": ["кроссовки"],
    "high-heeled shoes": ["туфли на высоком каблуке"],
    "slippers": ["тапочки"],
    "tracksuit": ["спортивный костюм"],
    "boxer shorts": ["трусы"],
    "accessories": ["аксессуары"],
    "knickers": ["дамские панталоны"],
    "dressing-gown": ["пеньюар домашний халат"],
    "a dressing gown": ["халат"],
    "a coat": ["пальто"]
]
