import Foundation

let House: [String:[String]] = [
    "to hang up the washing": ["вешать бельё"],
    "bucket": ["ведро"],
    "bathroom": ["ванная"],
    "bath": ["ванна"],
    "vase": ["ваза"],
    "alarm clock": ["будильник"],
    "to shave": ["бриться"],
    "balcony": ["балкон"],
    "video recorder": ["видеомагнитофон"],
    "to turn on": ["включить"],
    "to get up": ["встать"],
    "switch": ["выключатель"],
    "to turn off": ["выключить"],
    "to wipe": ["вытирать"],
    "lawn": ["газон"],
    "garage": ["гараж"],
    "wardrobe": ["гардероб"],
    "to iron": ["погладить"],
    "dirty": ["грязный"],
    "dirt": ["грязь"],
    "door": ["дверь"],
    "house": ["дом"],
    "at home": ["дома"],
    "oven": ["духовка"],
    "shower": ["душ"],
    "fence": ["забор"],
    "to close the curtains": ["задёрнуть занавески"],
    "to shut": ["закрыть"],
    "lock": ["замок"],
    "curtain": ["занавеска"],
    "to fall asleep": ["заснуть"],
    "mirror": ["зеркало"],
    "study": ["кабинет"],
    "fireplace": ["камин"],
    "picture": ["картина"],
    "flat": ["квартира"],
//    "key": ["ключ"],
    "bookcase": ["книжный шкаф"],
    "carpet": ["ковёр"],
    "room": ["комната"],
    "chest of drawers": ["комод"],
    "to paint": ["покрасить"],
    "armchair": ["кресло"],
    "bed": ["кровать"],
    "roof": ["крыша"],
    "stairs": ["лестница"],
    "to lie down": ["ложиться"],
    "to go to bed": ["лечь спать"],
    "tape recorder": ["магнитофон"],
    "furniture": ["мебель"],
    "broom": ["метла"],
    "microwave": ["микроволновая печь"],
    "freezer": ["морозильник"],
    "dustbin": ["мусорный ящик"],
    "shelf": ["полка"],
    "floor": ["пол"],
    "pillow": ["подушка"],
    "window sill": ["подоконник"],
    "cooker": ["плита"],
    "writing desk": ["письменный стол"],
    "to open": ["открыть"],
    "to open the curtains": ["открыть занавески"],
    "window": ["окно"],
    "blanket": ["одеяло"],
    "wallpaper": ["обои"],
    "scissors": ["ножницы"],
    "heater": ["нагреватель"],
    "outdoors": ["на улице"],
    "outside": ["на улице"],
    "to wash": ["мыться"],
    "soap": ["мыло"],
    "towel": ["полотенце"],
    "dishwasher": ["посудомоечная машина"],
    "ceiling": ["потолок"],
    "to take a bath": ["принять ванну"],
    "to take a shower": ["принять душ"],
    "to do / brush": ["причёсываться"],
    "CD-player": ["CD-проигрыватель"],
    "spacious": ["просторный"],
    "sheet": ["простыня"],
    "to wake up": ["просыпаться"],
    "vacuum cleaner": ["пылесос"],
    "to vacuum": ["пылесосить"],
    "dust": ["пыль"],
    "dusty": ["пыльный"],
    "radiator": ["радиатор"],
    "radio": ["радио"],
    "washbasin": ["раковина"],
    "socket": ["розетка"],
    "garden": ["сад"],
    "to sit down": ["садиться"],
    "light": ["светлый"],
    "bedroom": ["спальня"],
    "wall": ["стена"],
    "washing machine": ["стиральная машина"],
    "to do the washing": ["стирать бельё"],
    "table": ["стол"],
    "dining room": ["столовая"],
    "to build": ["построить"],
    "chair": ["стул"],
    "television": ["телевизор"],
    "telephone": ["телефон"],
    "dark": ["тёмный"],
    "cloth": ["тряпка"],
    "toilet": ["туалет"],
    "shampoo": ["шампунь"],
    "blind": ["штора"],
    "brush": ["щётка"],
    "drawer": ["ящик"],
    "clean": ["чистый"],
    "to brush one's teeth": ["почистить зубы"],
    "central heating": ["центральное отопление"],
    "refrigerator": ["холодильник"],
    "iron": ["утюг"],
    "convenient": ["удобный"],
    "to make the bed": ["убрать постель"],
    "to tidy the room": ["убрать комнату"],
    "dressing table": ["туалетный столик"],
    "adjacent": ["примыкающий"],
    "adorn": ["украшать"],
    "alcove": ["ниша", "альков"],
    "appliance": ["приспособление", "устройство", "прибор"],
    "apartment": ["квартира"],
    "basement": ["подвал", "фундамент"],
    "be cramped for space": ["мало места"],
    "be short of light": ["мало света"],
    "bedside table": ["тумбочка"],
    "bedspread": ["покрывало"],
    "block of flats": ["многоквартирный дом"],
    "block out the light": ["загораживать свет"],
    "building": ["здание"],
    "building society": ["строительное общество"],
    "bungalow": ["бунгало"],
    "bunk bed": ["двухъярусная кровать"],
    "camp bed": ["раскладушка"],
    "cellar": ["подвал", "погреб"],
    "chandelier": ["люстра"],
    "china": ["фарфор"],
    "closet": ["стенной шкаф", "чулан"],
    "coat rack": ["вешалка"],
    "coffee table": ["журнальный столик"],
    "convenience": ["удобство"],
    "cosy": ["уютный"],
    "cushion": ["диванная подушка"],
    "curtain rail": ["карниз"],
    "cupboard": ["шкаф", "сервант"],
    "crystal": ["хрусталь"],
    "cover": ["покрывало"],
    "country-house": ["загородный дом"],
    "cottage": ["коттедж", "домик"],
    "corridor": ["коридор"],
    "cooker hood": ["вытяжка"],
    "cutlery": ["ножевые изделия"],
    "decorate": ["оформлять", "украшать"],
    "detached house": ["отдельный дом"],
    "dinner set": ["столовый сервиз"],
    "dish-drainer": ["сушилка для посуды"],
    "door-handle ": ["дверная ручка"],
    "double bed": ["двуспальная кровать"],
    "dressing-table": ["туалетный столик"],
    "drive in a nail ": ["забить гвоздь"],
    "feel at home ": ["чувствовать себя как дома"],
    "fail to operate": ["сломаться"],
    "entrance": ["вход"],
    "dwelling": ["жилище"],
    "flush-toilet": ["унитаз"],
    "fluorescent lamp": ["лампа дневного света"],
    "flowered": ["цветастый"],
    "floor polisher": ["полотёр"],
    "floor parquet": ["пол паркетный"],
    "floor polished": ["пол натёртый"],
    "flight of stairs": ["лестничный пролёт"],
    "fitted carpet": ["палас", "ковровое покрытие"],
    "fridge": ["холодильник"],
    "housewarming party": ["новоселье"],
    "houseplant": ["комнатное растение"],
    "hedge": ["изгородь"],
    "hangings": ["портьеры"],
    "hall": ["прихожая"],
    "furnish": ["меблировать"],
    "front of the house": ["фасад дома"],
    "let a flat": ["сдавать квартиру"],
    "lavatory": ["туалет"],
    "lamp": ["лампа"],
    "know where things go": ["знать, где что лежит"],
    "kitchen": ["кухня"],
    "keyhole": ["замочная скважина"],
    "interior": ["интерьер"],
    "modem accomodations": ["современные удобства"],
    "mixer tap": ["смеситель", "кран"],
    "mat": ["коврик", "циновка"],
    "mansion": ["особняк", "большой дом"],
    "lustre": ["люстра"],
    "lounge": ["гостиная"],
    "living room": ["гостиная"],
    "linoleum": ["линолеум"],
    "lights go out": ["лампочки перегорают"],
    "lift": ["лифт"],
    "move the furniture around": ["передвигать мебель"],
    "move in": ["въезжать"],
    "move to": ["переезжать"],
    "mortgage": ["ипотека", "заём"],
    "patterned": ["с рисунком"],
    "parquet": ["паркет"],
    "papered": ["оклеенный обоями"],
    "palace": ["дворец"],
    "owner": ["владелец, собственник"],
    "two-storeyed house": ["двухэтажный дом"],
    "two-room flat": ["двухкомнатная квартира"],
    "nursery": ["детская комната"],
    "neighbour": ["сосед"],
    "refuse-chute ": ["мусоропровод"],
    "real estate agency": ["агентство недвижимости"],
    "quilt": ["стёганое одеяло"],
    "put things right": ["починить", "исправить"],
    "portable": ["переносной"],
    "pipes get clogged": ["трубы засоряются"],
    "pillow-case ": ["наволочка"],
    "show the dirt": ["пачкаться"],
    "shift": ["передвигать"],
    "self-contained flat": ["отдельная квартира"],
    "running water": ["водопровод"],
    "rug": ["пушистый коврик"],
    "rent a flat": ["снимать квартиру"],
    "repair": ["ремонт"],
    "renovate": ["подновлять", "ремонтировать", "реконструировать"],
    "sewing-machine": ["швейная машина"],
    "sofa": ["диван"],
    "sky-scraper": ["небоскрёб"],
    "sink": ["кухонная раковина"],
    "single bed": ["односпальная кровать"],
    "storeroom": ["кладовая"],
    "stool": ["табурет"],
    "stereo system": ["стереосистема"],
    "statuette": ["статуэтка"],
    "standard lamp": ["торшер"],
    "stack chairs": ["составлять стулья"],
    "spyhole": ["дверной глазок"],
    "space": ["место", "пространство"],
    "threshold": ["порог"],
    "throw open": ["распахнуть"],
    "TV set": ["телевизор"],
    "three quarter bed": ["полутораспальная кровать"],
    "tea set": ["чайный сервиз"],
    "tap": ["кран"],
    "stove": ["плита", "печь"],
    "waffle-maker": ["вафельница"],
    "vegetable cutter": ["овощерезка"],
    "utensil": ["посуда", "утварь"],
    "upholstery": ["обивка"],
    "upholstered furniture": ["мягкая мебель"],
    "unlock the door": ["отпереть дверь"],
    "tubular steel chair": ["стул с алюминиевыми ножками"],
    "tiled": ["покрытый кафельной плиткой"],
    "yard": ["двор"],
    "whitewash": ["побелка", "белить"],
    "washing wall-paper": ["моющиеся обои"],
    "wash-basin": ["умывальная раковина", "таз (умывальный)"],
    "wall units": ["стенка"],
    "wall-paper": ["обои"],
    "wall lamp": ["бра"]
]
