let Jobs: [String:[String]] = [
    "artist": ["художник"],
    "computer": ["компьютер"],
    "teacher": ["учитель"],
    "farmer": ["фермер"],
    "hairdresser": ["парикмахер"],
    "receptionist": ["портье", "администратор", "секретарь"],
    "desk": ["стол"],
    "uniform": ["униформа"],
    "break": ["перерыв"],
    "engineer": ["инженер"],
    "secretary": ["секретарь"],
    "manager": ["менеджер"],
    "occupation": ["оккупация"],
    "king": ["король"],
    "queen": ["королева"],
    "police officer": ["полицейский"],
    "chemist": ["химик"],
    "business": ["бизнес"],
    "earn": ["зарабатывать"],
    "guest": ["гость"],
    "customer": ["клиент"],
    "factory": ["завод"],
    "musician": ["музыкант"],
    "staff": ["персонал"],
    "barber": ["парикмахер"],
    "guide": ["руководство"],
    "journalist": ["журналист"],
    "mechanic": ["механик"],
    "painter": ["художник"],
    "driver": ["водитель"],
    "businessman": ["бизнесмен"],
    "businesswoman": ["деловая женщина"],
    "student": ["студент"],
    "tour guide": ["гид"],
    "cleaner": ["уборщик", "работник химчистки"],
    "job": ["работа"],
    "shop assistant": ["продавец"],
    "farm": ["ферма"],
    "diploma": ["диплом"],
    "meeting": ["встреча"],
    "work": ["работа"],
    "letter": ["письмо"],
    "office": ["офис"],
    "worker": ["работник"],
    "diary": ["дневник"],
    "company": ["компания"],
    "boss": ["босс"],
    "pharmacy": ["аптека"],
    "email": ["писать по электронной почте"],
    "message": ["сообщение"]
]
