let Land: [String:[String]] = [
    "coast": ["побережье"],
    "forest": ["лес"],
    "jungle": ["джунгли"],
    "rainforest": ["тропический лес"],
    "desert": ["пустыня"],
    "ocean": ["океан"],
    "peak": ["пик"],
    "oasis": ["оазис"],
    "swamp": ["болото"],
    "dam": ["плотина"],
    "plains": ["равнины"],
    "cave": ["пещера"],
    "volcano": ["вулкан"],
    "prairie": ["прерия"],
    "creek": ["ручей"],
    "steppe": ["степь"],
    "tundra": ["тундра"],
    "canyon": ["каньон"],
    "dune": ["дюна"],
    "grassland": ["поле"],
    "savanna": ["саванна"],
    "wasteland": ["пустошь"],
    "taiga": ["тайга"]
]
