let Marketing: [String:[String]] = [
    "promotion": ["продвижение"],
    "exhibition": ["выставка"],
    "goodwill": ["деловая репутация", "имидж"],
    "conflict of interest": ["конфликт интересов"],
    "workshop": ["семинар", "мастер-класс"],
    "target audience": ["целевая аудитория"],
    "briefing": ["короткая встреча официальных лиц с представителями СМИ"],
    "press kit": ["информационная подборка материалов для прессы"],
    "presentation": ["презентация"],
    "awards ceremony": ["церемония награждения"],
    "road show": ["серия презентаций", "серия выставок"],
    "public awareness": ["информирование общественности"],
    "newsbreak": ["инфоповод"],
    "press conference": ["пресс-конференция"],
    "Corporate Identity": ["фирменный стиль"],
    "code of conduct": ["кодекс поведения"],
    "chief information officer": ["руководитель информационной службы"],
    "community relations": ["связи с местным населением"],
    "public scrutiny": ["общественный контроль", "пристальное внимание общественности"],
    "corporate policy": ["корпоративная политика"],
    "public affairs": ["общественно-политические коммуникации", "работа с общественностью"],
    "PR practitioner": ["специалист по связям с общественностью"],
    "PR intern": ["PR-стажер"],
    "press adviser": ["советник по PR", "пресс-консультант"],
    "chief communications officer": ["руководитель коммуникационного отдела"],
    "PR executive": ["исполнительный директор по PR"],
    "publicity capital": ["паблицитный капитал"],
    "grassroots support": ["поддержка широких масс населения"],
    "stakeholder interest": ["заинтересованность участвующих сторон"],
    "reputation measurement": ["оценка репутации"],
    "a spokesperson": ["пресс-секретарь", "официальный представитель компании"],
    "to affect public opinion": ["влиять на общественное мнение"],
    "to gain favorable public opinion": ["заполучить благоприятное общественное мнение"],
    "to set ongoing long-term relations": ["установить постоянные долгосрочные отношения"],
    "to raise brand awareness": ["повысить узнаваемость бренда"],
    "to achieve new product acceptance": ["добиться принятия нового продукта"],
    "internal publics": ["внутренняя общественность"],
    "external publics": ["внешняя общественность"],
    "segmented groups": ["сегментированные группы"],
    "communications audit": ["коммуникационный аудит"],
    "corporate behavior": ["корпоративная культура"],
    "in-house magazine": ["корпоративный журнал"],
    "press tour": ["пресс-тур", "экскурсия для журналистов"],
    "welcome ceremony": ["церемония открытия"],
    "open house day": ["день открытых дверей"]
]
