let Sport: [String:[String]] = [
    "jogging": ["Бег трусцой"],
    "running": ["Бег"],
    "walking": ["Ходьба"],
    "skateboarding": ["Катание на скейтборде"],
    "bowling": ["Игра в кегли"],
    "horseback riding": ["Катание на лошади"],
    "skydiving": ["Прыжки с парашютом"],
    "golf": ["Гольф"],
    "tennis": ["Теннис"],
    "handball": ["Гандбол"],
    "ping pong": ["Настольный теннис"],
    "darts": ["Дротики"],
    "billiards": ["Биллиард"],
    "karate": ["Каратэ"],
    "gymnastics": ["Гимнастика"],
    "weightlifting": ["Тяжёлая атлетика"],
    "archery": ["Стрельба из лука"],
    "boxing": ["Бокс"],
    "basketball": ["Баскетбол"],
    "football": ["Футбол"],
    "swimming": ["Плавание"],
    "hockey": ["Хоккей"],
    "soccer": ["Футбол"],
    "baseball": ["Бейсбол"],
    "waterskiing": ["Катание на водных лыжах"],
    "wrestling": ["Борьба"],
    "volleyball": ["Волейбол"],
    "sailing": ["Парусный спорт"],
    "skating": ["Катание на коньках"],
    "skiing": ["Катание на лыжах"],
    "surfing": ["Сёрфинг"],
    "rowing": ["Гребля"],
    "canoeing": ["Катание на каноэ"],
    "rafting": ["Катание на плоту"],
    "Tobogganing": ["Катание на санях"],
    "Roller skating": ["Катание на роликах"],
    "Cycling/biking": ["Катание на велосипеде"]
]
